local G = GLOBAL
local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS

-- /////////////////////////////////////////////

STRINGS.NAMES.BLUEBERRIES = "Blueberries"
STRINGS.NAMES.BLUEBERRIES_COOKED = "Blueberry Jam"
STRINGS.NAMES.BLUEBERRIES_SEEDS = "Blueberry Seeds"

STRINGS.NAMES.BROCCOLI = "Broccoli"
STRINGS.NAMES.BROCCOLI_COOKED = "Cooked Broccoli"
STRINGS.NAMES.BROCCOLI_SEEDS = "Broccoli Seeds"

STRINGS.NAMES.CABBAGE = "Cabbage"
STRINGS.NAMES.CABBAGE_COOKED = "Cooked Cabbage"
STRINGS.NAMES.CABBAGE_SEEDS = "Cabbage Seeds"

STRINGS.NAMES.CAULIFLOWER = "Cauliflower"
STRINGS.NAMES.CAULIFLOWER_COOKED = "Cooked Cauliflower"
STRINGS.NAMES.CAULIFLOWER_SEEDS = "Cauliflower Seeds"

STRINGS.NAMES.LETTUCE = "Lettuce"
STRINGS.NAMES.LETTUCE_COOKED = "Ruined Lettuce"
STRINGS.NAMES.LETTUCE_SEEDS = "Lettuce Seeds"

STRINGS.NAMES.RASPBERRIES = "Raspberries"
STRINGS.NAMES.RASPBERRIES_COOKED = "Raspberry Jam"
STRINGS.NAMES.RASPBERRIES_SEEDS = "Raspberry Seeds"

STRINGS.NAMES.STRAWBERRIES = "Strawberries"
STRINGS.NAMES.STRAWBERRIES_COOKED = "Strawberry Jam"
STRINGS.NAMES.STRAWBERRIES_SEEDS = "Strawberry Seeds"

-- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Looks like a good treat"

-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Lil red globe"
-- STRINGS.CHARACTERS.WILLOW.DESCRIBE = "Looks yummy"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Looks like a good treat"

-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Lil red globe"
-- STRINGS.CHARACTERS.WARLY.DESCRIBE = "Looks yummy"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Looks like a good treat"

-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Lil red globe"
-- STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE = "Looks yummy"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Looks like a good treat"

-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Lil red globe"
-- STRINGS.CHARACTERS.WAXWELL.DESCRIBE = "Looks yummy"

-- /////////////////////////////////////////////

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BLUEBERRIES = "Lil sweet balls!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BLUEBERRIES_COOKED = "I want it on some toast"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BROCCOLI = "Looks like a tree!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BROCCOLI_COOKED = "It's all soft now"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.CABBAGE = "I could play football with it"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CABBAGE_COOKED = "It's not a ball anymore"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAULIFLOWER = "Not as romantic as regular flowers"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAULIFLOWER_COOKED = "It's all soft now"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.LETTUCE = "Good for salads"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LETTUCE_COOKED = "What even?"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.POTATO = "GIMME SOME 'TATOS"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.POTATO_COOKED = "That looks very tasty"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.RASPBERRIES = "Cute little fruits"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.RASPBERRIES_COOKED = "Very sweet"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.STRAWBERRIES = "The cutest of fruits"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.STRAWBERRIES_COOKED = "Looks like a good treat"

-- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WENDY.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WX78.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WX78.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WOLFGANG.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WINONA.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WOODIE.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WORMWOOD.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WORTOX.DESCRIBE = "Looks like a good treat"

-- -- /////////////////////////////////////////////

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "Lil sweet balls!"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "I want it on some toast"

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "Looks like a tree!"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "I could play football with it"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "It's not a ball anymore"

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "Not as romantic as regular flowers"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "It's all soft now"

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "Good for salads"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "What even?"

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "GIMME SOME 'TATOS"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "That looks very tasty"

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "Cute little fruits"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "Very sweet"

-- STRINGS.CHARACTERS.WURT.DESCRIBE = "The cutest of fruits"
-- STRINGS.CHARACTERS.WURT.DESCRIBE = "Looks like a good treat"