PrefabFiles = {
	"starvew_veggies"
	}

local G = GLOBAL
local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS
local RECIPETABS = GLOBAL.RECIPETABS
local TUNING = GLOBAL.TUNING

STRINGS.NAMES.BLUEBERRIES = "Blueberries"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Lil sweet balls!"
STRINGS.NAMES.BLUEBERRIES_COOKED = "Blueberry Jam"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "I want it on some toast"

STRINGS.NAMES.BROCCOLI = "Broccoli"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Looks like a tree!"
STRINGS.NAMES.BROCCOLI_COOKED = "Cooked Broccoli"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "It's all soft now"

STRINGS.NAMES.CABBAGE = "Cabbage"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "I could play football with it"
STRINGS.NAMES.CABBAGE_COOKED = "Cooked Cabbage"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "It's not a ball anymore"

STRINGS.NAMES.CAULIFLOWER = "Cauliflower"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Not as romantic as regular flowers"
STRINGS.NAMES.CAULIFLOWER_COOKED = "Cooked Cauliflower"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "It's all soft now"

STRINGS.NAMES.LETTUCE = "Lettuce"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Good for salads"
STRINGS.NAMES.LETTUCE_COOKED = "Ruined Lettuce"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "What even?"

STRINGS.NAMES.POTATO = "Potato"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "GIMME SOME 'TATOS"
STRINGS.NAMES.POTATO_COOKED = "Baked Potato"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "That looks very tasty"

STRINGS.NAMES.RASPBERRIES = "Raspberries"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Cute little fruits"
STRINGS.NAMES.RASPBERRIES_COOKED = "Raspberry Jam"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Very sweet"

STRINGS.NAMES.STRAWBERRIES = "Strawberries"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "The cutest of fruits"
STRINGS.NAMES.STRAWBERRIES_COOKED = "Strawberry Jam"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Looks like a good treat"

STRINGS.NAMES.TOMATO = "Tomato"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Lil red globe"
STRINGS.NAMES.TOMATO_COOKED = "Roasted Tomato"
STRINGS.CHARACTERS.GENERIC.DESCRIBE = "Looks yummy"
